-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -28.1399994, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -28, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.8600006, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.7199993, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.5799999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.4400005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.2999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.1599998, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.0200005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -26.8799992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -28.1399994, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -28, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.8600006, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.7199993, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.5799999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.4400005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.2999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.1599998, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.0200005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -26.8799992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3, true)
